# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_test1',
                'doc_host': 'https://Bakhytzhann.github.io',
                'git_url': 'https://github.com/Bakhytzhann/nbdev_test1',
                'lib_path': 'nbdev_test1'},
  'syms': {'nbdev_test1.core': {'nbdev_test1.core.foo': ('core.html#foo', 'nbdev_test1/core.py')}}}
